service: torrent-tracker-ip-checker

frameworkVersion: '>=2.0.0'

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs12.x
  endpointType: REGIONAL
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - '*/*'

functions:
  tracker:
    handler: build/index.trackerHandler
    events:
      - http:
          path: tracker
          method: get
  torrent:
    handler: build/index.torrentHandler
    events:
      - http:
          path: torrent
          method: get
